import React, { ComponentPropsWithoutRef, ReactNode } from 'react';

export type IconVariant =
  | 'icon-remove_red_eyevisibility'
  | 'icon-datepicker'
  | 'icon-instagram'
  | 'icon-casai-logo-white'
  | 'icon-checkmark'
  | 'icon-search'
  | 'icon-right-arrow'
  | 'icon-add'
  | 'icon-less'
  | 'icon-pax'
  | 'icon-close'
  | 'icon-Email-Icon'
  | 'icon-google'
  | 'icon-facebook'
  | 'icon-linkedin'
  | 'icon-Icon-Sign-In'
  | 'icon-check'
  | 'icon-Chevron-Down'
  | 'icon-Chevron-Left'
  | 'icon-Chevron-Right'
  | 'icon-Close'
  | 'icon-Search'
  | 'icon-Checked-Radio'
  | 'icon-Currency-and-Language'
  | 'icon-Casai-Logo-Color'
  | 'icon-notification'
  | 'icon-Badge-Facebook'
  | 'icon-Badge-Instagram'
  | 'icon-Badge-LinkedIn'
  | 'icon-Badge-TikTok'
  | 'icon-Badge-Twitter'
  | 'icon-Badge-Youtube'
  | 'icon-Gallery'
  | 'icon-Check-in-Check-out-time'
  | 'icon-Contact'
  | 'icon-Contact-Phone'
  | 'icon-Covid-Safety'
  | 'icon-Guest'
  | 'icon-Home'
  | 'icon-Location'
  | 'icon-Lugagge'
  | 'icon-Stay-time'
  | 'icon-Users'
  | 'icon-360'
  | 'icon-Amenities'
  | 'icon-Wifi'
  | 'icon-Building'
  | 'icon-Apartment'
  | 'icon-Cancellation-Policy'
  | 'icon-Bed'
  | 'icon-Bathroom'
  | 'icon-Clean-linens'
  | 'icon-Check-in'
  | 'icon-Extra-services'
  | 'icon-Exact-Location'
  | 'icon-Early-check-in'
  | 'icon-Getaway'
  | 'icon-Gym'
  | 'icon-Luxury-apartment'
  | 'icon-Parking'
  | 'icon-Clean'
  | 'icon-Late-check-out'
  | 'icon-Pet-friendly'
  | 'icon-Chromecast'
  | 'icon-Mask'
  | 'icon-Sanitize-surface'
  | 'icon-Check-out'
  | 'icon-Smart-Home-Devices'
  | 'icon-Saitary-kit'
  | 'icon-Square-meters'
  | 'icon-Slide-gesture'
  | 'icon-Work-space'
  | 'icon-Unit-rules'
  | 'icon-Smart-lock'
  | 'icon-TV'
  | 'icon-Info'
  | 'icon-Casai-club'
  | 'icon-Chat'
  | 'icon-Call-bell'
  | 'icon-Apartment1'
  | 'icon-Apartment-Details'
  | 'icon-Casai-Lounge'
  | 'icon-Chevron-Down1'
  | 'icon-Chevron-Up'
  | 'icon-Expand'
  | 'icon-Id-Card'
  | 'icon-Images'
  | 'icon-Information'
  | 'icon-Invoice'
  | 'icon-Modal'
  | 'icon-Open'
  | 'icon-Payment'
  | 'icon-Whatsapp'
  | 'icon-Bed-Outline'
  | 'icon-Calendar'
  | 'icon-Close-Outline'
  | 'icon-Guests'
  | 'icon-Promo-code'
  | 'icon-Checkmark'
  | 'icon-Warning'
  | 'icon-Loading-dots'
  | '';
export type IconProps = {
  variant: IconVariant;
  children?: ReactNode;
} & ComponentPropsWithoutRef<'span'>;

export const Icon = ({
  variant,
  className = '',
  children,
  ...props
}: IconProps) => {
  return (
    <span className={`icon ${variant} ${className}`} {...props}>
      {children !== undefined ? children : null}
    </span>
  );
};
